### ISSUE TITLE
sftp access with password to containers

### ISSUE THREAD

**Issue by xrmx** [unbit/uwsgi.it#18]
It would be nice to be able to create accounts that can access a path of the container filesystem through sftp with password authentication. These users should not have access to a shell just to sftp-server. The use case is a replacement for ftp which some customers are still in love to.

**Comment by unbit** [comment]
Users wanting 90's approach will be able to buy a dedicated ip address (i am currently defining the api for managing them) and directly map it to the container. This will solve basically any non-expected use case

**Comment by xrmx** [comment]
Mmm there's a good chunk of people still in the 90s tech wise, you recently added an ftp client so you should be aware of that ;) Whatever you'll end up with is fine for me. Thanks!
