### ISSUE TITLE
Package request for postgis support

### ISSUE THREAD

**Issue by difra** [unbit/uwsgi.it#88]
Please add postgis, postgresql-9.3-postgis-2.1, postgresql-9.3-postgis-scripts.
Thank you.

**Comment by unbit** [comment]
do you need them for a specific distro ?

**Comment by difra** [comment]
Ubuntu 14.04 LTS. 
Thank you.

**Comment by unbit** [comment]
hi they are already available

**Comment by difra** [comment]
I'm sorry. It was my fault. Now it's works.
